"""
DynamoDB Stream Handler with Retry Logic

Generated by AI Orchestration Layer (Demo #4)
Implements exponential backoff for transient DynamoDB errors.
"""
import time
import random
import logging
from functools import wraps
from typing import Dict, Any, Callable

logger = logging.getLogger(__name__)


class RetryableError(Exception):
    """Error that should trigger a retry"""
    pass


def exponential_backoff(
    max_retries: int = 5,
    base_delay: float = 0.1,
    max_delay: float = 10.0,
    jitter: bool = True,
):
    """
    Decorator for exponential backoff retry logic.
    
    Args:
        max_retries: Maximum number of retry attempts
        base_delay: Initial delay in seconds
        max_delay: Maximum delay cap in seconds
        jitter: Whether to add randomness to delay
    """
    def decorator(func: Callable) -> Callable:
        @wraps(func)
        def wrapper(*args, **kwargs):
            last_exception = None
            
            for attempt in range(max_retries + 1):
                try:
                    return func(*args, **kwargs)
                except (RetryableError, Exception) as e:
                    last_exception = e
                    
                    if attempt >= max_retries:
                        logger.error(f"Max retries ({max_retries}) exceeded: {e}")
                        raise
                    
                    delay = min(base_delay * (2 ** attempt), max_delay)
                    
                    if jitter:
                        delay += random.uniform(0, delay * 0.1)
                    
                    logger.warning(
                        f"Retry {attempt + 1}/{max_retries} after {delay:.2f}s: {e}"
                    )
                    time.sleep(delay)
            
            raise last_exception
        return wrapper
    return decorator


@exponential_backoff(max_retries=5, base_delay=0.1, max_delay=10.0)
def process_dynamodb_record(record: Dict[str, Any]) -> None:
    """Process a single DynamoDB stream record with retry."""
    event_name = record.get('eventName', 'UNKNOWN')
    event_id = record.get('eventID', 'unknown')
    
    logger.info(f"Processing {event_name}: {event_id}")


def handler(event: Dict[str, Any], context: Any) -> Dict[str, Any]:
    """Lambda handler for DynamoDB stream events."""
    records = event.get('Records', [])
    processed = 0
    failed = 0
    
    for record in records:
        try:
            process_dynamodb_record(record)
            processed += 1
        except Exception as e:
            logger.error(f"Failed to process record: {e}")
            failed += 1
    
    return {
        'statusCode': 200,
        'body': {
            'processed': processed,
            'failed': failed,
            'total': len(records),
        }
    }
